name: VyOS v1.2 LTS Release

on:
  push:
    tags:
      - 'v1.2.*'

env:
  GIT_CLONE_URL: https://github.com/vyos/vyos-build
  BRANCH: crux
  ARCHITECTURE: amd64
  BUILD_BY: vyos-build-action@github.com
  BUILD_TYPE: release
  DEBIAN_MIRROR: http://ftp.us.debian.org/debian/

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: vyos/vyos-build:crux
      options: --workdir /vyos --privileged
    
    steps:
      - name: Clone source code
        run: git clone -b $BRANCH --single-branch $GIT_CLONE_URL
        
      - name: Build ISO
        working-directory: ./vyos-build
        run: |
          ./configure --architecture $ARCHITECTURE --build-by $BUILD_BY --build-type $BUILD_TYPE --version ${GITHUB_REF##*v}
          sudo make iso
          
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: vyos-${GITHUB_REF##*v}-${{ env.ARCHITECTURE }}-iso
          path: vyos-build/build/vyos-${GITHUB_REF##*v}-*.iso

  release:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: vyos-${GITHUB_REF##*v}-${{ env.ARCHITECTURE }}-iso
          path: vyos-${GITHUB_REF##*v}-${{ env.ARCHITECTURE }}-iso

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: VyOS LTS Release ${{ github.ref }}
          body: VyOS LTS Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload release asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: vyos-${GITHUB_REF##*v}-${{ env.ARCHITECTURE }}-iso/vyos-${GITHUB_REF##*v}-${{ env.ARCHITECTURE }}.iso
          asset_name: vyos-${GITHUB_REF##*v}-${{ env.ARCHITECTURE }}.iso
          asset_content_type: application/octet-stream
